apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "trino-configfiles, trino-catalog, kafka-table-description-dir"
    secret.reloader.stakater.com/reload: "s3buckets, trino-oauth, trino-secret-env"
  name: trino-coordinator
  labels:
    instance: trino
    role: trino-coordinator
spec:
  selector:
    matchLabels:
      instance: trino
      role: trino-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        instance: trino
        role: trino-coordinator
    spec:
      volumes:
        - name: trino-config-volume
          configMap:
            name: trino-configfiles
            defaultMode: 420
        - name: trino-catalogs-volume
          configMap:
            name: trino-catalog
            defaultMode: 420
        - name: kafka-table-description-dir
          configMap:
            name: kafka-table-description-dir
            defaultMode: 420
        - name: prometheus-exporter
          secret:
            secretName: trino-config-monitoring
            defaultMode: 420
            items:
              - key: config.yaml
                path: config.yaml
      containers:
        - resources:
            requests:
              cpu: $(trino_cpu_request)
              memory: $(trino_memory_request)
            limits:
              cpu: $(trino_cpu_limit)
              memory: $(trino_memory_limit)
          name: trino-coordinator
          command:
            - /usr/lib/trino/bin/run-trino
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.uid
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: trino-config-volume
              mountPath: /etc/trino
            - name: prometheus-exporter
              mountPath: /etc/trino/prometheus
            - name: trino-catalogs-volume
              mountPath: /etc/trino/catalog
            - name: kafka-table-description-dir
              mountPath: /etc/kafka/table-description-dir
          image: trino
          envFrom:
            - secretRef:
                name: trino-oauth
            - secretRef:
                name: s3buckets
            - secretRef:
                name: shared-secret
            - secretRef:
                name: trino-secret-env
          args:
            - --config=/etc/trino/config-coordinator.properties
            - --jvm-config=/etc/trino/jvm-coordinator.config
